/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NetApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NetApiTests
    {
        private NetApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NetApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' NetApi
            //Assert.IsInstanceOf(typeof(NetApi), instance);
        }

        
        /// <summary>
        /// Test PublicMinersFailuresMinerGet
        /// </summary>
        [Test]
        public void PublicMinersFailuresMinerGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string miner = null;
            //var response = instance.PublicMinersFailuresMinerGet(miner);
            //Assert.IsInstanceOf(typeof(string), response, "response is string");
        }
        
        /// <summary>
        /// Test PublicMinersGet
        /// </summary>
        [Test]
        public void PublicMinersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PublicMinersGet();
            //Assert.IsInstanceOf(typeof(string), response, "response is string");
        }
        
        /// <summary>
        /// Test PublicNetAddrsGet
        /// </summary>
        [Test]
        public void PublicNetAddrsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PublicNetAddrsGet();
            //Assert.IsInstanceOf(typeof(List<string>), response, "response is List<string>");
        }
        
        /// <summary>
        /// Test PublicNetPeersGet
        /// </summary>
        [Test]
        public void PublicNetPeersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PublicNetPeersGet();
            //Assert.IsInstanceOf(typeof(List<string>), response, "response is List<string>");
        }
        
    }

}
