/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserApiTests
    {
        private UserApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' UserApi
            //Assert.IsInstanceOf(typeof(UserApi), instance);
        }

        
        /// <summary>
        /// Test UserApiKeysGet
        /// </summary>
        [Test]
        public void UserApiKeysGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.UserApiKeysGet();
            //Assert.IsInstanceOf(typeof(List<MainGetApiKeysResp>), response, "response is List<MainGetApiKeysResp>");
        }
        
        /// <summary>
        /// Test UserApiKeysKeyDelete
        /// </summary>
        [Test]
        public void UserApiKeysKeyDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string key = null;
            //var response = instance.UserApiKeysKeyDelete(key);
            //Assert.IsInstanceOf(typeof(string), response, "response is string");
        }
        
        /// <summary>
        /// Test UserApiKeysPost
        /// </summary>
        [Test]
        public void UserApiKeysPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string perm = null;
            //string expiry = null;
            //var response = instance.UserApiKeysPost(perm, expiry);
            //Assert.IsInstanceOf(typeof(MainGetApiKeysResp), response, "response is MainGetApiKeysResp");
        }
        
        /// <summary>
        /// Test UserExportGet
        /// </summary>
        [Test]
        public void UserExportGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.UserExportGet();
            //Assert.IsInstanceOf(typeof(string), response, "response is string");
        }
        
        /// <summary>
        /// Test UserStatsGet
        /// </summary>
        [Test]
        public void UserStatsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.UserStatsGet();
            //Assert.IsInstanceOf(typeof(MainUserStatsResponse), response, "response is MainUserStatsResponse");
        }
        
    }

}
