/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MainEstimateDealBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MainEstimateDealBodyTests
    {
        // TODO uncomment below to declare an instance variable for MainEstimateDealBody
        //private MainEstimateDealBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MainEstimateDealBody
            //instance = new MainEstimateDealBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MainEstimateDealBody
        /// </summary>
        [Test]
        public void MainEstimateDealBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MainEstimateDealBody
            //Assert.IsInstanceOf(typeof(MainEstimateDealBody), instance);
        }


        /// <summary>
        /// Test the property 'DurationBlks'
        /// </summary>
        [Test]
        public void DurationBlksTest()
        {
            // TODO unit test for the property 'DurationBlks'
        }
        /// <summary>
        /// Test the property 'Replication'
        /// </summary>
        [Test]
        public void ReplicationTest()
        {
            // TODO unit test for the property 'Replication'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Test]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }

    }

}
