/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MainAddContentToCollectionParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MainAddContentToCollectionParamsTests
    {
        // TODO uncomment below to declare an instance variable for MainAddContentToCollectionParams
        //private MainAddContentToCollectionParams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MainAddContentToCollectionParams
            //instance = new MainAddContentToCollectionParams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MainAddContentToCollectionParams
        /// </summary>
        [Test]
        public void MainAddContentToCollectionParamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MainAddContentToCollectionParams
            //Assert.IsInstanceOf(typeof(MainAddContentToCollectionParams), instance);
        }


        /// <summary>
        /// Test the property 'Cids'
        /// </summary>
        [Test]
        public void CidsTest()
        {
            // TODO unit test for the property 'Cids'
        }
        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Test]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }
        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Test]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }

    }

}
