/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MainGetApiKeysResp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MainGetApiKeysRespTests
    {
        // TODO uncomment below to declare an instance variable for MainGetApiKeysResp
        //private MainGetApiKeysResp instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MainGetApiKeysResp
            //instance = new MainGetApiKeysResp();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MainGetApiKeysResp
        /// </summary>
        [Test]
        public void MainGetApiKeysRespInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MainGetApiKeysResp
            //Assert.IsInstanceOf(typeof(MainGetApiKeysResp), instance);
        }


        /// <summary>
        /// Test the property 'Expiry'
        /// </summary>
        [Test]
        public void ExpiryTest()
        {
            // TODO unit test for the property 'Expiry'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

    }

}
