/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MainUserStatsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MainUserStatsResponseTests
    {
        // TODO uncomment below to declare an instance variable for MainUserStatsResponse
        //private MainUserStatsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MainUserStatsResponse
            //instance = new MainUserStatsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MainUserStatsResponse
        /// </summary>
        [Test]
        public void MainUserStatsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MainUserStatsResponse
            //Assert.IsInstanceOf(typeof(MainUserStatsResponse), instance);
        }


        /// <summary>
        /// Test the property 'NumPins'
        /// </summary>
        [Test]
        public void NumPinsTest()
        {
            // TODO unit test for the property 'NumPins'
        }
        /// <summary>
        /// Test the property 'TotalSize'
        /// </summary>
        [Test]
        public void TotalSizeTest()
        {
            // TODO unit test for the property 'TotalSize'
        }

    }

}
