/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UtilContentAddIpfsBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UtilContentAddIpfsBodyTests
    {
        // TODO uncomment below to declare an instance variable for UtilContentAddIpfsBody
        //private UtilContentAddIpfsBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UtilContentAddIpfsBody
            //instance = new UtilContentAddIpfsBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UtilContentAddIpfsBody
        /// </summary>
        [Test]
        public void UtilContentAddIpfsBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UtilContentAddIpfsBody
            //Assert.IsInstanceOf(typeof(UtilContentAddIpfsBody), instance);
        }


        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Test]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }
        /// <summary>
        /// Test the property 'CollectionPath'
        /// </summary>
        [Test]
        public void CollectionPathTest()
        {
            // TODO unit test for the property 'CollectionPath'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Peers'
        /// </summary>
        [Test]
        public void PeersTest()
        {
            // TODO unit test for the property 'Peers'
        }
        /// <summary>
        /// Test the property 'Root'
        /// </summary>
        [Test]
        public void RootTest()
        {
            // TODO unit test for the property 'Root'
        }

    }

}
